apiVersion: v1
kind: Service
metadata:
  name: uptime-kuma
spec:
  type: LoadBalancer
  selector:
    app: uptime-kuma
  ports:
    - name: http
      port: 3001
      targetPort: 3001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime-kuma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uptime-kuma
  template:
    metadata:
      labels:
        app: uptime-kuma
    spec:
      containers:
        - name: uptime-kuma
          image: louislam/uptime-kuma:1
          volumeMounts:
            - name: uptime-kuma-data
              mountPath: /app/data
          ports:
            - containerPort: 3001
          env:
            - name: TZ
              value: "Europe/Dublin"
      volumes:
        - name: uptime-kuma-data
          hostPath:
            path: /path/to/uptime-kuma-data
      restartPolicy: Always
